[package]
name = "collada"
version = "0.1.0"
authors = ["Oliver Bøving <oliverboving@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde-xml-rs = "*"
failure = "0.1"
